
services:
  db:
    image: postgres:15
    container_name: crm_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crm_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:  # Add health check
      test: ["CMD-SHELL", "pg_isready -U user -d crm_db"]
      interval: 5s
      timeout: 5s
      retries: 10  

  web:
    build: .
    container_name: fastapi_crm_web
    depends_on:
      db:
        condition: service_healthy  # Wait for DB to be healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

volumes:
  postgres_data:
